actors:
  ysdyt:
    image_url: /images/actors/yutatatatata.jpg
    name: ysdyt
    url: https://twitter.com/yutatatatata
  sorami:
    image_url: /images/actors/sorami.jpg
    name: Sorami Hisamoto
    url: https://twitter.com/sorami
  tenjimn:
    image_url: /images/actors/tenjimn.jpeg
    name: tenjimn
    url: https://twitter.com/tenjimn
  ryo_astro:
    image_url: /images/actors/ryo_astro.jpeg
    name: 佐々木亮
    url: https://twitter.com/_ryo_astro
  tatsuki_2022:
    image_url: /images/actors/tatsuki_2022.jpeg
    name: たっちゃん
    url: https://twitter.com/tatsuki_2022
  srt_taka:
    image_url: /images/actors/srt_taka.jpeg
    name: Takayuki Saruta
    url: https://twitter.com/srt_taka
  karaage0703:
    image_url: /images/actors/karaage0703.jpeg
    name: からあげ
    url: https://twitter.com/karaage0703
author: 界隈.chat
description: いろんな界隈について話すpodcast番組
description_long: いろんな界隈について話すpodcast番組
email: kaiwaichat@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: kaiwaichat
itunes_podcast_url: https://podcasts.apple.com/us/podcast/界隈-chat/id1680389809
keywords: data science,AI
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: 界隈.chat
url: https://kaiwai.chat
